import re

raw_list = [
  'Paul Atreides', 'Lady Jessica', 'Leto I Atreides', 'Vladimir Harkonnen', 'Chani', 'Stilgar', 'Duncan Idaho', 'Wellington Yueh', 'Gaius Helen Mohiam', 'Beast Rabban', 'Feyd-Rautha', 'Princess Irulan', 'Shaddam IV', 'Gurney Halleck', 'Count Fenring', 'Margot Fenring', 'Thufir Hawat', 'Alia Atreides', 'Shadout Mapes', 'Liet-Kynes', 'Ramallo', 'Jamis', 'Harah', 'Piter De Vries', 'Scytale', 'Edric', 'Bijaz', 'Lichna', 'Farok', 'Princess Wensicia', 'Leto II Atreides', 'Ghanima Atreides', 'Tyekanik', 'Namri', 'Javid', 'Faradn', 'Siona Atreides', 'Hwi Noree', 'Anteac', 'Moneo Atreides', 'Nayla', 'Chenoeh', 'Lucilla', 'Miles Teg', 'Murbella', 'Darwi Odrade', 'Sheeana', 'Tylwyth Waff', 'Bellonda', 'Taraza', 'Burzmali', 'Hedley Tuek', 'Rebecca', 'Daniel', 'Marty', 'Dama', 'Logno', 'Dortujla', 'Anirul', 'Elrood IX', 'Serena Butler', 'Xavier Harkonnen', 'Vorian Atreides', 'Iblis Ginjo', 'Norma Cenva', 'Raquella Berto-Anirul', 'Doria', 'Hellica', 'Valya Harkonnen', 'Griffin Harkonnen', 'Dorotea', 'Tula Harkonnen', 'Albert Atreides', 'Aman Wutin', 'Aramsham', 'Arjen Gates', 'Assan Tariq', 'Avila', 'Baron Yaoufirks', 'Kinet', 'Korba', 'Lady Hagal', 'Ledden Pook', 'Wanna Yueh', 'Hayt', 'Paulus Atreides', 'Helena Atreides', 'Kailea Vernius', 'Victor Atreides', 'Rhombur Vernius', 'Glossu Rabban', 'Ziarenko Javid', 'Luyseyal', 'Sheeana Brugh', 'Alma Mavis Taraza', 'Alef Burzmali', 'Otheym', 'Muriz', 'Tessia', 'Ctair Pilru', 'Dmurr Pilru', 'Cammar Pilru', 'Tyros Repha', 'Count Ilban Richese', 'Iago Kurin', 'Whitmore Bludd', 'Esmar Tuek', 'Staban Tuek', 'Tuek', 'Lingar Tykanik', 'Zhufa Szur', 'Erasmus', 'Omnius', 'Ajax', 'Agamemnon', 'Barbarossa', 'Dante', 'Juno', 'Xerxes', 'Hecate', 'Tlaloc', 'Seurat', 'Gilbertus Albans', 'Rayna Szento', 'Manion Butler', 'Livia Butler', 'Faykan Butler', 'Quentin Butler', 'Waff', 'Scytale the Elder', 'Master Zaaf', 'Master Tleilaxu', 'Khrone', 'Udir', 'Hidar Fen Ajidica', 'Marie Fenring', 'Viktor Atreides', 'Leto II the Elder', 'Abulurd Harkonnen', 'Tanidia Nerus', 'Lord Niko Bludd', 'Count Memnon Thorvald', 'Lady Elmi Thorvald', 'Dominic Vernius', 'Lady Shando Balut', 'Archduke Armand Ecaz', 'Princess Ilesa Ecaz', 'Princess Sanda Ecaz', 'Viscount Hundro Moritani', 'Lupino Ord',
  'Arrakis', 'Barandiko', 'Beakkal', 'Bela Tegeuse', 'Biarek', 'Buzzell', 'Caladan', 'Cedon', 'Chapterhouse', 'Chusuk', 'Corrin', 'Crompton', 'Dur', 'Earth', 'Ecaz', 'Enfiel', 'Gaar', 'Galicia', 'Gammu', 'Gamont', 'Gansireed', 'Giedi Prime', 'Ginaz', 'Grumman', 'Hagal', 'Harmonthep', 'Hessra', 'Ishkal', 'Ishia', 'Ix', 'Rodale IX', 'Xuttah', 'Otorio', 'Parella', 'Parmentier', 'Pilargo', 'Pincknon', 'Ponciard', 'Poritrin', 'Quadra', 'Reenol', 'Relicon', 'Renditai', 'Richese', 'Roc', 'Romo', 'Ros-Jal', 'Rossak', 'Salusa Secundus', 'Semboule', 'Seneca', 'Seprek', 'Sikun', 'Souci',
  'Amtal', 'Antifatigue pills', 'Aql', 'Arcana', 'Arifa', 'Armored Screen', 'Arrakeen', 'Assassins Handbook', 'Atomics', 'Auliya', 'Aumas', 'Auqaf', 'Axlotl tank', 'Ayat', 'Ayil', 'Bahada', 'Bahr bela ma', 'Bakka', 'Baklawa', 'Baliset', 'Barachan', 'Bindu', 'Bindu Suspension', 'Biyan', 'Bled', 'Body temperature pills', 'Book of Kreos', 'Book Leto', 'Bourka', 'Bravos', 'Bu Ji', 'Burhan', 'Bureau of faith', 'Burseg', 'Butlerian Jihad', 'Cadelam', 'Caid', 'Caliph', 'Coif', 'Cold Air Walls', 'ComNet', 'Cone of silence', 'Coriolis storm', 'Crusher', 'Cryologic tank', 'The Crypt', 'Crysknife', 'Cueshma', 'Cutterray', 'Cymek',
  'Bene Gesserit', 'Bene Tleilax', 'Spacing Guild', 'Landsraad', 'CHOAM', 'Sardaukar', 'Fremen', 'Mentat', 'Fish Speakers', 'Honored Matres', 'Face Dancers', 'Swordmasters of Ginaz', 'Suk School', 'Truthsayers', 'Guild Navigators', 'House Atreides', 'House Harkonnen', 'House Corrino', 'House Fenring', 'House Vernius', 'House Richese', 'House Ecaz', 'House Thorvald', 'House Mutelli', 'House Ginaz', 'Sandtrout', 'Sandworm', 'Futar', 'Chairdogs', 'Slig', 'Laza Tiger', 'Desert Hare', 'Kit-fox', 'Kangaroo mouse', 'Eagle', 'Hawk', 'Steer', 'Wild Ass', 'Sloth-bear', 'Ornithopter', 'Glowglobe', 'Stillsuit', 'Lasgun', 'Holtzman Shield', 'Thumper', 'Hunter-seeker', 'Heighliner'
]

def clean(s):
    s = s.lower().strip()
    s = re.sub(r'[^a-z0-9]', '_', s)
    s = re.sub(r'_+', '_', s)
    return s.strip('_')

cleaned = sorted(list(set([clean(t) for t in raw_list])))
for t in cleaned:
    print(f'    \"{t}\",')
print(f'// Total: {len(cleaned)}')
